---
uid: OpcUaSystemComponentConfig
---

# Configure system components

<!--include explanation of system components in this section. --> 

<hr style="border:2px solid gray">

## Configuration methods {.tabset}

### EdgeCmd Utility

Use EdgeCmd utility to add and remove adapter components, and to configure facets of the components.

**Note:** The examples in this topic are using the default port number 5590. If you specified a different port number for your adapter or EDS, you need to add it in the command. For example:

```bash
edgecmd -port 5591 <RestOfTheCommand>
```

**Note:** If a command contains slashes, you must add escape characters as follows:

- In Windows, add a second slash. </br>
Example: TestUser\OilCompany becomes TestUser\\OilCompany

- In Linux, add three additional slashes. </br>
Example: TestUser\OilCompany becomes TestUser\\\\OilCompany

#### Add components
Complete the following steps to add a new component:

1. Access EdgeCmd utility through the command line.

2. Type the following in the command line, replacing <componentType> and <componentId> with the values for the component and press Enter.

    ```bash
    edgecmd add Components [-type <componentType>] [-id <componentId>]
    ```
    **Example:** OPC UA adapter component registration

    ```bash
    edgecmd add Components -type OpcUa -id OpcUa1
    ```

#### Configure a facet of a component
All adapters have different configurable facets. Complete the following steps to configure a facet:

1. Access EdgeCmd utility through the command line.
2. Type the following in the command line, replacing <facetName> and <componentId> with their respective values. Then press Enter.
    ```bash
    edgecmd set <facetName> -cid <componentId> [-file <filepath>]
    ```

    **Example:** Configuration of the data source facet of an OPC UA adapter

    ```bash
    edgecmd set DataSource -cid OpcUa1 -file C:\Users\TestUser\OpcUa1\DataSource.json
    ```

#### Remove a component
Complete the following steps to remove a component from the adapter or EDS:

1. Access EdgeCmd utility through the command line.
2. Type the following in the command line, replacing <componentId> with the ID of the component to remove, and press Enter. Edgecmd prompts with "Please Confirm [y/N]: " unless you include the optional -y parameter.

    ```bash
    edgecmd remove Components [-id <componentId] [-y]
    ```
    **Example:** Removal of the OPC UA component
    
    ```bash
    edgecmd remove Components -id OpcUa1
    ```
    **Note:** You cannot remove the OmfEgress from PI adapters or the Storage component from EDS. They are required for the products to operate.

<hr style="border:2px solid gray">

### cUrl

#### Configure system components

Complete the following steps to configure system components. Use the `PUT` method in conjunction with the `http://localhost:5590/api/v1/configuration/system/components` REST endpoint to initialize the configuration.

1. Use a text editor to create an empty text file.

2. Copy and paste an example configuration for system components into the file.

    For sample JSON, see [Examples](#examples).

3. Update the example JSON parameters for your environment.

    For a table of all available parameters, see [System components parameters](#system-components-parameters).

4. Save the file. For example, as `ConfigureComponents.json`.

5. Open a command line session. Change directory to the location of `ConfigureComponents.json`.

6. Enter the following cURL command (which uses the `PUT` method) to initialize the system components configuration.

    ```bash
    curl -d "@ConfigureComponents.json" -H "Content-Type: application/json" -X PUT "http://localhost:5590/api/v1/configuration/system/components"
    ```

    **Notes:**
  
    * If you installed the adapter to listen on a non-default port, update `5590` to the port number in use.
    * For a list of other REST operations you can perform, like updating or deleting a system components configuration, see [REST URLs](#rest-urls).

<hr style="border:2px solid gray">

## System components schema

The full schema definition for the system components configuration is in the `System_Components_schema.json` file located in one of the following folders:

Windows: `%ProgramFiles%\OSIsoft\Adapters\AdapterName\Schemas`

Linux: `/opt/OSIsoft/Adapters/AdapterName/Schemas`

## System components parameters

You can configure the following parameters for system components:

| Parameters     | Required | Type    | Description |
| -------------- | -------- | --------| -------------|
| **ComponentId**    | Required |`string` | The ID of the component 1  . It can be any alphanumeric string. A properly configured ComponentID follows these rules:Cannot contain leading or trailing space  Cannot use the following characters: `>` `<` `/` `:` `?` `#` `[` `]` `@` `!` `$` `&` `*` `"` `(` `)` `\\` `+` `,` `;` `=` `|` `` ` `` `{` `}`**Note:** The **ComponentId** is added to each container message that an adapter component sends to an OMF endpoint. It is displayed as the data source information (point source) in PI Web API. |
| **ComponentType**  | Required |`string` | The type of the component. There are two types of components: OmfEgress and the adapter. 1  |
    
 1 **Note:** The OmfEgress component is required to run the adapter. Both its **ComponentId** and **ComponentType** are reserved and should not be modified.

## Examples

### Default system components configuration

The default _System_Components.json_ file for the System component contains the following information.

```json
[
  {
    "ComponentId": "OmfEgress",
    "ComponentType": "OmfEgress"
  }
]
```

### System components configuration with two adapter instances

```json
[
    {
        "componentId": "OpcUa1",
        "componentType": "OpcUa"
    },
    {
        "componentId": "OpcUa2",
        "componentType": "OpcUa"
    },
    {
        "componentId": "OmfEgress",
        "componentType": "OmfEgress"
    }
]
```

## REST URLs

| Relative URL | HTTP verb | Action |
| ------------ | --------- | ------ |
| api/v1/configuration/system/components | GET | Retrieves  the system components configuration |
| api/v1/configuration/system/components | POST | Adds a new component to the system configuration |
| api/v1/configuration/system/components | PUT | Updates the system components configuration |
| api/v1/configuration/system/components/_ComponentId_ | DELETE | Deletes a specific component from the system components configuration |
| api/v1/configuration/system/components/_ComponentId_ | PUT | Creates a new component with the specified *ComponentId* in the system configuration